### ISSUE TITLE
parse problem with backslash

### ISSUE THREAD

**Issue by gil-n** [taskcluster/gdb-js#5]
hi,

another issue with parsing results:
this time the result is:
**^done,value="0x3a3f90 '\253' <repeats 16 times>, \"\356\376\356\376\356\376\356\376\356\376\356\376\356\376\356\376\""
(gdb)** 

events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Expected "[", "[]", "{", "{}", or c-string but "\"" found.
    at peg$buildStructuredError (C:\_projects\debugger\test\vscode-mock-debug\node_modules\gdb-js\lib\gdbmi.js:381:12)
    at peg$parse (C:\_projects\debugger\test\vscode-mock-debug\node_modules\gdb-js\lib\gdbmi.js:1453:11)

**Comment by gil-levy** [comment]
how's this as a solution?

 function escaper(match, p1, p2, offset, string) {
        var ret = ''
        for (var i = 0; i < p1.length * 2; i++) {
            ret += '\\'
        }
        return ret + p2
    }

 let stream = _(this._process.stdout)
      .map((chunk) => chunk.toString().replace(/(\\+)(\d|\w)/g, escaper))
      .splitBy(/\r\n|\n/)
      .tap(debugOutput)
      .map(parseMI)

**Comment by gil-n** [comment]
how's this for a solution?

function escaper(match, p0, p1, offset, string) {
    return (p0.length % 2 !== 0) ? p0 + '\\\\' + p1 : p0 + p1
}

chunk.toString().replace(/(\\\\+)(\\d|\\w)/g, escaper)

**Comment by baygeldin** [comment]
Well, there are two problems I see. The first is a problem with a slash which is solved easily by updating the peg parser (the third line here is a solution):
```javascript
Char "char"
  = [\x20-\x21\x23-\x5B\x5D-\u10FFFF]
  / "\\" [\x20-\x21\x23-\x5B\x5D-\u10FFFF] { return text() }
  / "\\" seq:Escaped { return seq }
```
However, the parser will still fail on quotes, because for some reason they are not escaped in your output. If I remember correctly, gdb should escape all quotes in output. So it is either a problem with your output (e.g. you copied it from somewhere else where quotes were unescaped, but in plain gdb the output is actually `^done,value="0x3a3f90 '\253' <repeats 16 times>, \"\356\376\356\376\356\376\356\376\356\376\356\376\356\376\356\376\""`) or gdb sometimes returns unescaped strings. In the latter case we have a problem which is not even solvable with the PEG formalism.

**Comment by gil-n** [comment]
Good morning.

The peg fix works well.
As for the quotes, there's no issue, i guess the escaped quotes were removed on the copy paste.

Is the npm package updated with these changes?
Thanks

**Comment by gil-n** [comment]
probably the same problem of handling uninitialized variables in python using context method:

{ GDBError: Error while executing "-interpreter-exec console **"gdbjs-context""**. Error occurred in Python command: 'ascii' codec can't encode characters in position 108-109: ordinal not in range(128)
    at GDBError.Error (native)
    at new GDBError (C:\_projects\debugger\test\vscode-mock-debug\node_modules\gdb-js\lib\index.js:2226:83)


**update:**
changing the value from str to unicode solves the problem, don't know if that's the right way to go
 variables.append({
                        "name": symbol.name,
                        "value": unicode(symbol.value(frame)),
                        "type": str(symbol.type),
                        "scope": scope
                    })

**update2:** unicode seems problematic, it works but it may change the output (not sure)

**Comment by baygeldin** [comment]
@gil-levy thanks for input. I didn't look deeply into the issue and thus misunderstood the problem. These "\nnn" numbers are clearly special characters that were escaped by gdb. The current peg parser handles only limited set of special characters (e.g. quotes and new lines). So, a good solution would be to force gdb to display special characters as is. In order to do that execute `gdb.set('print sevenbit-strings', 'off')` before you call other methods. This will work to some extent, I hope. If it works for you, I will include it into the next release. Btw, discard the fix I proposed — it's redundant.

**Comment by gil-n** [comment]
hi,

Setting print sevenbit-strings to 'off' doesn't solve the problem.

For now using: unicode(symbol.value(frame)) works but as i said I'm not sure it's 100% correct
Or maybe should be: unicode(symbol.value(frame)).encode('utf-8')

**Comment by baygeldin** [comment]
Okay, seems like python output is a separate problem. Setting `print sevenbit-strings off` only solves the problem for MI output (e.g. for commands like `-stack-list-variables 1`). As for python, I believe it is better to change `res = json.dumps(self.action(arg, from_tty))` to `res = json.dumps(self.action(arg, from_tty), ensure_ascii=False)` in `base.py` leaving the `str(symbol.value(frame))` line in `context.py` unchanged. However, I'm not 100% sure that it will work with python 2  since I checked it with python 3. Btw, what python version you're using? You can check it by executing `python import sys; print(sys.version);` in your gdb.

**Comment by gil-n** [comment]
hi Alexander,

I've tested your suggestions and here are the results:
1.**call gdb.set('print sevenbit-strings', 'off')** instead of your pegjs fix 
not working: SyntaxError: Expected "[", "[]", "{", "{}", or c-string but "\"" found.
the original fix of changing the pegjs works well.

2.**Python version:** 
python import sys; print(sys.version);
&"python import sys; print(sys.version);\n"
~"2.7.9 (default, Sep  8 2016, 14:03:45) \n[GCC 6.2.0]"

3.**res = json.dumps(self.action(arg, from_tty))** this fails on "value": str(symbol.value(frame)) ascii encoding before reaching the json.dumps... code 
unicode(symbol.value(frame)).encode('utf-8') - seems to work

**Comment by baygeldin** [comment]
As I thought it would fail on that line because python 2 `unicode` is python 3 `str`. The correct way to make it compatible with both python versions is to add `from builtins import str` to `context.py`, I guess. However, it will probably require to install the `future` module (by `pip install future`). Another workaround is to manually check whether the `unicode` method exists:
```python
import gdb


class ContextCommand(BaseCommand):
    """Lists all symbols in the current context."""

    def __init__(self):
        super(ContextCommand, self).__init__("context")

    def action(self, arg, from_tty):
        frame = gdb.selected_frame()
        block = frame.block()
        names = set()
        variables = []
        while block:
            for symbol in block:
                name = symbol.name
                if (name not in names) and (symbol.is_argument or
                   symbol.is_variable or symbol.is_function or
                   symbol.is_constant):
                    scope = "global" if block.is_global else \
                            "static" if block.is_static else \
                            "argument" if symbol.is_argument else \
                            "local"
                    names.add(name)
                    value = symbol.value(frame)
                    try:
                        # Python 2.x
                        value = unicode(value)
                    except NameError:
                        # Python 3.x
                        value = str(value)
                    variables.append({
                        "name": symbol.name,
                        "value": value,
                        "type": str(symbol.type),
                        "scope": scope
                    })
            block = block.superblock
        return variables

gdbjsContext = ContextCommand()
```

As for pegjs fix, it works, but it does not convert unicode characters which is not right.  These `\nnn` numbers are useless in JS, so all unicode characters should be converted beforehand (by gdb itself). I don't know why is `print sevenbit-strings` option not working for you though. Can you please describe what commands you're calling in more detail?

**Comment by gil-n** [comment]
this is my initialization code:
  ```
      opts = opts || []
        opts.push('-i=mi')
        exec = exec.replace(/\\/g, '/')
        this.child = spawn('gdb', opts)
        this.gdb = new GDB(this.child)
        await this.gdb.init()
        await this.gdb.execMI(`-file-exec-and-symbols ${exec}`)
        await this.gdb.set('print sevenbit-strings', 'off')
```

later i'm getting values of variables, if a variable is uninitialized it looks as follows:
info locals
&"info locals\n"
~"FR = {prev = 0x4, procname = 0x23fcb8 \"-\""
~", line = 140731110407424"
~", filename = 0x7ffe83cfd593 <msvcrt!fflush+51> \"\213\307H\213\\\\$8H\203\304
_\303\", '\\220' <repeats 16 times>, \"H\211\\\\$\\020H\211t$\\030\211L$\\bWATAUAVAWH\203\3540E\213\360D\213\372Hc\331\203\373\376\\017\204\\003N\\003\""
~", len = 0"
~", calldepth = 0"
~"}"
~"\n"
^done

**Comment by baygeldin** [comment]
Sorry for delay, I was kind of busy lately. Anyway, I tried to test it with older versions of gdb and python. Turns out that it works differently in many cases and indeed proposed solutions don't really solve the problem. I looked into gdb mi sources and found out that `sevenbit_strings` option alone is not enough. We will still get `\nnn` here and there: 
```c
#define PRINT_LITERAL_FORM(c) \
  ((c) >= 0x20 \
   && ((c) < 0x7F || (c) >= 0xA0) \
   && (!sevenbit_strings || (c) < 0x80))
```
Encoding in gdb mi is not that easy after all and it is quite inconsistent. So, in my opinion the safest way would be to convert these octal escape sequences manually in pegjs. This will solve the problem for both MI and CLI commands. We can already convert `\uxxxx` unicode sequences to actual unicode characters by using `JSON.parse` (e.g. `JSON.parse('"\\u00e4"')`). What I can't figure out for now is how to convert `\nnn` octal sequences to `\uxxxx` unicode sequences in JS (e.g. how to convert `\303\244` to `\u00e4`). I'll look into this a bit later. Let me know if you have an idea.

**Comment by baygeldin** [comment]
Hmm, I've just tried another approach. It seems like it works albeit it looks like a hack :)
It requires only a couple new lines in the parser:
```javascript
Const "c-string"
  = "\"" chars:Char* "\"" { return decodeURIComponent(chars.join('')) } // new line

Char "char"
  = [\x20-\x21\x23-\x5B\x5D-\u10FFFF]
  / "\\" octal:([0-7][0-7][0-7]) { return "%" + parseInt(octal.join(''), 8).toString(16) } // new line
  / "\\" seq:Escaped { return seq }
```
I'll try to test it and if it works out I'll release a new version.

**Comment by baygeldin** [comment]
@gil-levy so I released the 1.2.0. I fixed the rules a bit in order to avoid some obvious bugs. However, I tested everything locally, because the regression test I implemented didn't work because of [weird GDB MI behavior in a Docker container](https://github.com/taskcluster/gdb-js/commit/ea76f38b500418d1d20f579b4fdb5f7a62b590f7#diff-faa503f61f8addeb603095cc2f40c82eR484).  I hope it will work (if you use Python 2.x you'll also need to install `future` with `pip`). If not, then I'll have to put this issue on hold until there is a way to test it automatically.

**Comment by gil-n** [comment]
I think that fixing the peg parser is the way to go, the parser just needs to pass on the data as is.

**Comment by baygeldin** [comment]
Yeah, that's a good idea. However, this way we won't be able to test python commands, because they don't go through the parser. Besides, I'm still not sure which one is the correct output to test against, so let's just see how the current fix will work.
